/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gaming_room.glb 
Author: Barisart (https://sketchfab.com/Barisart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-room-f344194edece414fb0ead7993cf63a43
Title: Gaming room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Game_room(props) {
  const { nodes, materials } = useGLTF('models/gaming_room.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 11.058, -13.164]} scale={[18.498, 0.198, 23.431]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.External_Floor_Arizona} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.tembok} />
      </group>
      <group position={[-16.23, 9.607, -8.941]} scale={[0.098, 1.451, 3.091]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-12.947, 7.235, -11.604]} scale={[0.356, 0.153, 0.157]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.key_caps} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-13.53, 7.294, -45.375]} rotation={[Math.PI / 2, 0, 0]} scale={[0.07, 0.021, 0.07]}>
        <mesh geometry={nodes.Object_20.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Material.011']} />
      </group>
      <group position={[-12.982, 7.046, -9.077]} scale={[1.283, 0.027, 3.649]}>
        <mesh geometry={nodes.Object_23.geometry} material={materials.mouse_pad} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-15.116, 2.409, 2.348]} scale={[2.413, 2.413, 2.042]}>
        <mesh geometry={nodes.Object_30.geometry} material={materials.pintu_lemari_kecil} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.kayu} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Material} />
      </group>
      <group position={[-16.198, 16.872, -9.989]} rotation={[0, 0, -0.146]} scale={[0.275, 4.075, 6.965]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.key_caps} />
      </group>
      <group position={[15.331, 9.73, 20.669]} rotation={[0, Math.PI / 2, 0]} scale={[2.146, 9.572, 6.627]}>
        <mesh geometry={nodes.Object_39.geometry} material={materials.kayu} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.pintu_lemari_kecil} />
      </group>
      <group position={[12.496, 2.367, -10.056]} rotation={[-Math.PI, 0, -Math.PI]} scale={[3.359, 2.244, 8.934]}>
        <mesh geometry={nodes.Object_42.geometry} material={materials.sofa} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.pintu_lemari_kecil} />
      </group>
      <group position={[15.349, 24.005, 21.391]} rotation={[0, Math.PI / 2, 0]} scale={[1.281, 1.281, 5.268]}>
        <mesh geometry={nodes.Object_51.geometry} material={materials.pintu_lemari_kecil} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.key_caps} />
      </group>
      <group position={[-15.107, 9.884, -4.131]} rotation={[0, 0.665, 0]} scale={[0.098, 1.155, 2.6]}>
        <mesh geometry={nodes.Object_54.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_55.geometry} material={materials['Material.016']} />
      </group>
      <group position={[-16.098, 8.266, 1.215]} scale={0.476}>
        <mesh geometry={nodes.Object_57.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Object_58.geometry} material={materials['Material.019']} />
      </group>
      <group position={[-12.661, 3.726, -15.094]} rotation={[0, 0, -0.429]} scale={[1.047, 0.092, 0.956]}>
        <mesh geometry={nodes.Object_62.geometry} material={materials.key_caps} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.merah_metalic} />
      </group>
      <group position={[-16.602, 13.727, 8.077]} scale={0.738}>
        <mesh geometry={nodes.Object_69.geometry} material={materials.key_caps} />
        <mesh geometry={nodes.Object_70.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_71.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-13.978, 7.496, 1.578]} rotation={[0, 0, Math.PI / 2]} scale={[-0.029, 1.15, 0.855]}>
        <mesh geometry={nodes.Object_73.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_74.geometry} material={materials['Material.008']} />
      </group>
      <group position={[-13.177, 7.487, 3.599]} rotation={[0, 0.41, Math.PI / 2]} scale={[-0.026, 1.009, 0.75]}>
        <mesh geometry={nodes.Object_76.geometry} material={materials.key_caps} />
        <mesh geometry={nodes.Object_77.geometry} material={materials['Material.013']} />
      </group>
      <group position={[-15.122, 12.401, -11.741]} scale={12.433}>
        <mesh geometry={nodes.Object_91.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_92.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Object_93.geometry} material={materials['Material.021']} />
      </group>
      <group position={[-12.386, 15.828, 22.526]} rotation={[0, Math.PI / 2, 0]} scale={[0.149, 5.866, 10.224]}>
        <mesh geometry={nodes.Object_95.geometry} material={materials.dasar_gorden} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.tembok} />
      </group>
      <group position={[-14.57, 7.067, -14.638]} rotation={[0, -0.736, 0]} scale={[1.161, 0.069, 2.059]}>
        <mesh geometry={nodes.Object_120.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_121.geometry} material={materials['Material.018']} />
      </group>
      <group position={[-15.53, 8.229, -15.508]} rotation={[0, -0.736, -1.396]} scale={[1.161, 0.046, 2.059]}>
        <mesh geometry={nodes.Object_123.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Object_124.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-16.551, 14.215, 18.475]} scale={[1.016, 1.253, 0.235]}>
        <mesh geometry={nodes.Object_128.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_129.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-16.551, 14.215, 17.992]} scale={[1.016, 1.253, 0.235]}>
        <mesh geometry={nodes.Object_131.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_132.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-16.551, 14.215, 17.51]} scale={[1.016, 1.253, 0.235]}>
        <mesh geometry={nodes.Object_134.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_135.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-16.551, 14.215, 17.028]} scale={[1.016, 1.253, 0.235]}>
        <mesh geometry={nodes.Object_137.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_138.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-16.551, 14.215, 16.545]} scale={[1.016, 1.253, 0.235]}>
        <mesh geometry={nodes.Object_140.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_141.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-16.551, 14.23, 15.882]} rotation={[0.137, 0, 0]} scale={[1.016, 1.253, 0.235]}>
        <mesh geometry={nodes.Object_143.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_144.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-16.551, 14.23, 15.384]} rotation={[0.137, 0, 0]} scale={[1.016, 1.253, 0.235]}>
        <mesh geometry={nodes.Object_148.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_149.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-16.551, 13.079, 12.573]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[1.016, 1.253, 0.235]}>
        <mesh geometry={nodes.Object_151.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_152.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-15.22, 1.159, -8.91]} rotation={[0, 0, -1.564]} scale={[0.543, 0.424, 0.543]}>
        <mesh geometry={nodes.Object_156.geometry} material={materials.key_caps} />
        <mesh geometry={nodes.Object_157.geometry} material={materials.abu2_metalic} />
      </group>
      <group position={[-15.202, 1.159, -7.454]} rotation={[0, 0, -1.564]} scale={[0.543, 0.424, 0.543]}>
        <mesh geometry={nodes.Object_163.geometry} material={materials.key_caps} />
        <mesh geometry={nodes.Object_164.geometry} material={materials.abu2_metalic} />
      </group>
      <group position={[-15.238, 1.159, -10.328]} rotation={[0, 0, -1.564]} scale={[0.543, 0.424, 0.543]}>
        <mesh geometry={nodes.Object_166.geometry} material={materials.key_caps} />
        <mesh geometry={nodes.Object_167.geometry} material={materials.abu2_metalic} />
      </group>
      <group position={[-15.293, 7.551, -6.545]} rotation={[0, 0, -Math.PI / 2]} scale={[0.218, 0.243, 0.218]}>
        <mesh geometry={nodes.Object_169.geometry} material={materials.key_caps} />
        <mesh geometry={nodes.Object_170.geometry} material={materials.abu2_metalic} />
      </group>
      <group position={[-15.293, 7.551, -11.447]} rotation={[0, 0, -Math.PI / 2]} scale={[0.218, 0.243, 0.218]}>
        <mesh geometry={nodes.Object_172.geometry} material={materials.key_caps} />
        <mesh geometry={nodes.Object_173.geometry} material={materials.abu2_metalic} />
      </group>
      <mesh geometry={nodes.Object_7.geometry} material={materials.kayu} position={[-7.988, 1.522, 13.268]} scale={[9.616, 1.459, 7.714]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.003']} position={[-7.988, 4.447, 13.268]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.pine_wood} position={[-13.899, 6.743, -10.045]} scale={[2.88, 0.275, 7.439]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Material.004']} position={[-15.014, 5.964, 12.789]} rotation={[0, 0, -0.085]} scale={[1.762, 0.087, 3.719]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['Material.004']} position={[-6.723, 11.549, 13.201]} scale={[8.9, 1.133, 8.168]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.kayu} position={[-15.292, 12.738, 13.064]} scale={[2.788, 0.145, 7.458]} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.bantal_sofa_kecil} position={[14.152, 6.288, -3.179]} rotation={[-Math.PI, 0, 1.809]} scale={[1.835, 0.081, 1.66]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.abu2_metalic} position={[16.053, 9.612, 17.97]} rotation={[0, Math.PI / 2, 0]} scale={[0.114, 0.453, 0.071]} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.abu2_metalic} position={[-12.344, 1.353, 1.949]} rotation={[Math.PI / 2, 0, 0]} scale={[0.114, 0.453, 0.071]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.key_caps} position={[-13.986, 1.873, -15.016]} rotation={[0, 0, -0.035]} scale={[2.055, 0.063, 0.987]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.merah_metalic} position={[-11.967, 2.658, -15.055]} rotation={[0, 0, -1.606]} scale={[0.129, 0.053, 0.129]} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.merah_metalic} position={[-11.961, 2.41, -15.055]} rotation={[0, 0, -1.606]} scale={[0.076, 0.031, 0.076]} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.keyboard} position={[-13.099, 7.15, -8.299]} scale={[0.714, 0.074, 2.058]} />
      <mesh geometry={nodes.Object_81.geometry} material={materials['Material.014']} position={[-13.369, 7.276, -7.939]} scale={[0.1, 0.029, 0.1]} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.space} position={[-13.369, 7.276, -7.939]} scale={[0.1, 0.029, 0.1]} />
      <mesh geometry={nodes.Object_85.geometry} material={materials.space} position={[-13.369, 7.276, -7.939]} scale={[0.1, 0.029, 0.1]} />
      <mesh geometry={nodes.Object_87.geometry} material={materials.key_caps} position={[-13.369, 7.276, -7.939]} scale={[0.1, 0.029, 0.1]} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.space} position={[-13.369, 7.276, -7.939]} scale={[0.1, 0.029, 0.1]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.pintu_lemari_kecil} position={[-13.761, 20.878, 21.896]} rotation={[0, Math.PI / 2, 0]} scale={[0.482, 0.482, 0.28]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.pintu_lemari_kecil} position={[5.082, 20.878, 21.896]} rotation={[0, Math.PI / 2, 0]} scale={[0.482, 0.482, 0.28]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.abu2_metalic} position={[-4.353, 20.899, 22.222]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.13, 9.62, 0.13]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.pintu_lemari_kecil} position={[-4.92, 19.73, 22.216]} rotation={[0, Math.PI / 2, 0]} scale={[0.036, 1.143, 1.143]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.pintu_lemari_kecil} position={[-13.779, 16.63, 21.792]} rotation={[0, Math.PI / 2, 0]} scale={[0.073, 3.861, 0.073]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials['Material.004']} position={[-7.131, 0.534, -11.483]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.335, 0.058, 0.335]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.abu2_metalic} position={[-7.131, 0.676, -10.89]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.03, 0.143, 0.03]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials['Material.004']} position={[-8.66, 1.505, -8.459]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.378, 0.182, 0.147]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.space} position={[-7.206, 6.516, -6.049]} rotation={[0, -Math.PI / 2, 0]} scale={[0.284, 0.099, 1.674]} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.hexgon_light} position={[-17.759, 19.391, 17.714]} scale={[0.088, 0.928, 1]} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.pintu_lemari_kecil} position={[-15.661, 7.158, -14.092]} rotation={[0, -0.736, 0]} scale={[0.102, 0.015, 0.091]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials.abu2_metalic} position={[-16.551, 14.216, 18.784]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.189, 1.319, 0.048]} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.abu2_metalic} position={[-16.551, 14.216, 14.906]} scale={[-0.189, 1.319, 0.048]} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.tembok} position={[-15.405, 1.148, -8.908]} rotation={[0, 0, 0.007]} scale={[0.497, 0.933, 2.303]} />
      <mesh geometry={nodes.Object_159.geometry} material={materials.pintu_lemari_kecil} position={[-15.506, 7.477, -6.566]} scale={0.395} />
      <mesh geometry={nodes.Object_161.geometry} material={materials.pintu_lemari_kecil} position={[-15.506, 7.477, -11.416]} scale={0.395} />
    </group>
  )
}

useGLTF.preload('models/gaming_room.glb')
